version: '3.4'
services:
  es-sql:
    image: sunnywalden/elasticsearch-with-sql:v0.1.4
    ports:
      - 9502:9200
      - 9503:9300
      - 9508:8088
    networks:
      - tezign
    volumes:
      - /data/es_search_v5_with_sql/config:/usr/share/elasticsearch/config
      - /data/es_search_v5_with_sql/logs:/usr/share/elasticsearch/logs
      - /data/es_search_v5_with_sql/plugins:/usr/share/elasticsearch/plugins
      - /data/es_search_v5_with_sql/data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ="Asia/Shanghai"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stop_grace_period: 30s
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
      update_config:
        parallelism: 1
        delay: 0s
        failure_action: rollback
        max_failure_ratio: 0
        order: start-first
      replicas: 1
      resources:
        limits:
          memory: 8192MB
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: 'curl 127.0.0.1:9200 || exit 1'
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  tezign:
#    external: true
